name : CI/CD React - Vite - Github Actions - CloudRun

on:
   push : 
        branches : 
               - main

jobs:
    build-and-deploy : 
        name : Build and Deploy
        runs-on: unbuntu-latest

        steps:
          - name : Checkout Source Code
            uses : actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: npm

          - name: Install dependencies
            run: npm install --force

          - name: Build Vite application
            run: npm run build
          
    
          
        
 
    
 